# MEISTROVERSE Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MEISTROVERSE application
  - job_name: 'meistroverse'
    static_configs:
      - targets: ['meistroverse:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MySQL database
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
    scrape_interval: 30s

  # Redis cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node exporter (if added)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # Nginx (if metrics enabled)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx:9113']